### ISSUE TITLE
HTTPS for Website

### ISSUE THREAD

**Issue by Nutomic** [duplicati/duplicati.github.io#1]
I wanted to install Duplicati, but it seems like there is no way to safely download it. The [website](http://www.duplicati.com) does not support HTTPS, and the same releas doesn't seem to be available on Github. This is a huge security risk, because an attacker can intercept all downloads.

**Comment by kenkendk** [comment]
I agree completely, unfortunately that is not currently possible unless we start hosting the site ourselves:
https://github.com/isaacs/github/issues/156

For a safe download, you can use this page, it has the same entries:
https://github.com/duplicati/duplicati/releases

The updates are also fetched over plain HTTP, but they are signed with a private key.

**Comment by Nutomic** [comment]
I didn't know that the downloads on Github are the same ones as on the website (mostly because of the complicated version names). In this case, why don't you point the download links directly to the files on Github? 

Edit: Of course that wouldn't solve the problem entirely, as an attacker could still change the links on the website.

**Comment by kenkendk** [comment]
I prefer to keep control over the targets. If I use github as the target, the links stop working if github decides to change the url layouts.

I have just finished deploying a new CDN that has https support, so now the download links are https, but the website itself is still not https. Fixing this is on my TODO.

The next builds will also request update files over https.

**Comment by aviraccoon** [comment]
You could set up HTTPS on CloudFlare. I know, not the best solution, but it feels a bit better for me than not having any certificate for the website.

Or move the website to GitLab Pages. They support adding your own certs on custom domains.

**Comment by kenkendk** [comment]
I have just updated the server system, such that `www.duplicati.com` is now hosted on another server, and has SSL certificate. It redirects HTTP traffic to that.

The root domain `duplicati.com` is not currently served over https, but redirects to `www.duplicati.com`
