### ISSUE TITLE
Please warn that 1.x is completely not supported anymore

### ISSUE THREAD

**Issue by Yvan-Masson** [duplicati/duplicati.github.io#8]
Hi,

I wanted to use Duplicati for important data, and so I thought I would use 1.3.4, which is advertised on the website homepage. However, after carefully watching bug reports, I found that important problems are not investigated for this version (see https://github.com/duplicati/duplicati/issues/1018).

I completely understand that you do not have the manpower to maintain the 1.x version, but please write it clearly to avoid other big mistakes and problems.

Still many thanks for the work done on this software, hoping for a stable 2.0 !

**Comment by kenkendk** [comment]
Good point.

I have updated the text on the button.
